[package]
name = "faculator-app"
version.workspace = true
edition.workspace = true

[dependencies]
faculator-data = { path = "../../library/data" }

tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"] }
color-eyre = "0.6.5"
sea-orm = { version = "1.1.14", features = ["sqlx-sqlite", "sqlite-use-returning-for-3_35", "runtime-tokio", "macros"] }
serde_json = "1.0.142"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
