// @generated by `facx codegen category`. Do not edit manually.
use faculator_macros::string_enum;

string_enum! {
    /// fuel 类别边界。
    pub enum FuelCategory {
        Chemical => "chemical",
        Food => "food",
        Fusion => "fusion",
        Nuclear => "nuclear",
        Nutrients => "nutrients",
    }
}
