// @generated by `facx codegen category`. Do not edit manually.
use faculator_macros::string_enum;

string_enum! {
    /// recipe 类别边界。
    pub enum RecipeCategory {
        AdvancedCrafting => "advanced-crafting",
        BasicCrafting => "basic-crafting",
        CaptiveSpawnerProcess => "captive-spawner-process",
        Centrifuging => "centrifuging",
        Chemistry => "chemistry",
        ChemistryOrCryogenics => "chemistry-or-cryogenics",
        Crafting => "crafting",
        CraftingWithFluid => "crafting-with-fluid",
        CraftingWithFluidOrMetallurgy => "crafting-with-fluid-or-metallurgy",
        Crushing => "crushing",
        Cryogenics => "cryogenics",
        CryogenicsOrAssembling => "cryogenics-or-assembling",
        Electromagnetics => "electromagnetics",
        Electronics => "electronics",
        ElectronicsOrAssembling => "electronics-or-assembling",
        ElectronicsWithFluid => "electronics-with-fluid",
        Metallurgy => "metallurgy",
        MetallurgyOrAssembling => "metallurgy-or-assembling",
        OilProcessing => "oil-processing",
        Organic => "organic",
        OrganicOrAssembling => "organic-or-assembling",
        OrganicOrChemistry => "organic-or-chemistry",
        OrganicOrHandCrafting => "organic-or-hand-crafting",
        Parameters => "parameters",
        Pressing => "pressing",
        Recycling => "recycling",
        RecyclingOrHandCrafting => "recycling-or-hand-crafting",
        RocketBuilding => "rocket-building",
        Smelting => "smelting",
    }
}
