// @generated by `facx codegen category`. Do not edit manually.
use faculator_macros::string_enum;

string_enum! {
    /// resource 类别边界。
    pub enum ResourceCategory {
        BasicFluid => "basic-fluid",
        BasicSolid => "basic-solid",
        HardSolid => "hard-solid",
    }
}
